// Code generated by ent, DO NOT EDIT.

package projectview

import (
	"silan-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldProjectID, v))
}

// UserIdentityID applies equality check predicate on the "user_identity_id" field. It's identical to UserIdentityIDEQ.
func UserIdentityID(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldUserIdentityID, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldFingerprint, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldIPAddress, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldUserAgent, v))
}

// Referrer applies equality check predicate on the "referrer" field. It's identical to ReferrerEQ.
func Referrer(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldReferrer, v))
}

// SessionDuration applies equality check predicate on the "session_duration" field. It's identical to SessionDurationEQ.
func SessionDuration(v int) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldSessionDuration, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldProjectID, vs...))
}

// UserIdentityIDEQ applies the EQ predicate on the "user_identity_id" field.
func UserIdentityIDEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldUserIdentityID, v))
}

// UserIdentityIDNEQ applies the NEQ predicate on the "user_identity_id" field.
func UserIdentityIDNEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldUserIdentityID, v))
}

// UserIdentityIDIn applies the In predicate on the "user_identity_id" field.
func UserIdentityIDIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldUserIdentityID, vs...))
}

// UserIdentityIDNotIn applies the NotIn predicate on the "user_identity_id" field.
func UserIdentityIDNotIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldUserIdentityID, vs...))
}

// UserIdentityIDGT applies the GT predicate on the "user_identity_id" field.
func UserIdentityIDGT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGT(FieldUserIdentityID, v))
}

// UserIdentityIDGTE applies the GTE predicate on the "user_identity_id" field.
func UserIdentityIDGTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGTE(FieldUserIdentityID, v))
}

// UserIdentityIDLT applies the LT predicate on the "user_identity_id" field.
func UserIdentityIDLT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLT(FieldUserIdentityID, v))
}

// UserIdentityIDLTE applies the LTE predicate on the "user_identity_id" field.
func UserIdentityIDLTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLTE(FieldUserIdentityID, v))
}

// UserIdentityIDContains applies the Contains predicate on the "user_identity_id" field.
func UserIdentityIDContains(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContains(FieldUserIdentityID, v))
}

// UserIdentityIDHasPrefix applies the HasPrefix predicate on the "user_identity_id" field.
func UserIdentityIDHasPrefix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasPrefix(FieldUserIdentityID, v))
}

// UserIdentityIDHasSuffix applies the HasSuffix predicate on the "user_identity_id" field.
func UserIdentityIDHasSuffix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasSuffix(FieldUserIdentityID, v))
}

// UserIdentityIDIsNil applies the IsNil predicate on the "user_identity_id" field.
func UserIdentityIDIsNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIsNull(FieldUserIdentityID))
}

// UserIdentityIDNotNil applies the NotNil predicate on the "user_identity_id" field.
func UserIdentityIDNotNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotNull(FieldUserIdentityID))
}

// UserIdentityIDEqualFold applies the EqualFold predicate on the "user_identity_id" field.
func UserIdentityIDEqualFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEqualFold(FieldUserIdentityID, v))
}

// UserIdentityIDContainsFold applies the ContainsFold predicate on the "user_identity_id" field.
func UserIdentityIDContainsFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContainsFold(FieldUserIdentityID, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintIsNil applies the IsNil predicate on the "fingerprint" field.
func FingerprintIsNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIsNull(FieldFingerprint))
}

// FingerprintNotNil applies the NotNil predicate on the "fingerprint" field.
func FingerprintNotNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotNull(FieldFingerprint))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContainsFold(FieldFingerprint, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIsNull(FieldIPAddress))
}

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotNull(FieldIPAddress))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContainsFold(FieldIPAddress, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContainsFold(FieldUserAgent, v))
}

// ReferrerEQ applies the EQ predicate on the "referrer" field.
func ReferrerEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldReferrer, v))
}

// ReferrerNEQ applies the NEQ predicate on the "referrer" field.
func ReferrerNEQ(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldReferrer, v))
}

// ReferrerIn applies the In predicate on the "referrer" field.
func ReferrerIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldReferrer, vs...))
}

// ReferrerNotIn applies the NotIn predicate on the "referrer" field.
func ReferrerNotIn(vs ...string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldReferrer, vs...))
}

// ReferrerGT applies the GT predicate on the "referrer" field.
func ReferrerGT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGT(FieldReferrer, v))
}

// ReferrerGTE applies the GTE predicate on the "referrer" field.
func ReferrerGTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGTE(FieldReferrer, v))
}

// ReferrerLT applies the LT predicate on the "referrer" field.
func ReferrerLT(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLT(FieldReferrer, v))
}

// ReferrerLTE applies the LTE predicate on the "referrer" field.
func ReferrerLTE(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLTE(FieldReferrer, v))
}

// ReferrerContains applies the Contains predicate on the "referrer" field.
func ReferrerContains(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContains(FieldReferrer, v))
}

// ReferrerHasPrefix applies the HasPrefix predicate on the "referrer" field.
func ReferrerHasPrefix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasPrefix(FieldReferrer, v))
}

// ReferrerHasSuffix applies the HasSuffix predicate on the "referrer" field.
func ReferrerHasSuffix(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldHasSuffix(FieldReferrer, v))
}

// ReferrerIsNil applies the IsNil predicate on the "referrer" field.
func ReferrerIsNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIsNull(FieldReferrer))
}

// ReferrerNotNil applies the NotNil predicate on the "referrer" field.
func ReferrerNotNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotNull(FieldReferrer))
}

// ReferrerEqualFold applies the EqualFold predicate on the "referrer" field.
func ReferrerEqualFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEqualFold(FieldReferrer, v))
}

// ReferrerContainsFold applies the ContainsFold predicate on the "referrer" field.
func ReferrerContainsFold(v string) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldContainsFold(FieldReferrer, v))
}

// SessionDurationEQ applies the EQ predicate on the "session_duration" field.
func SessionDurationEQ(v int) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldSessionDuration, v))
}

// SessionDurationNEQ applies the NEQ predicate on the "session_duration" field.
func SessionDurationNEQ(v int) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldSessionDuration, v))
}

// SessionDurationIn applies the In predicate on the "session_duration" field.
func SessionDurationIn(vs ...int) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldSessionDuration, vs...))
}

// SessionDurationNotIn applies the NotIn predicate on the "session_duration" field.
func SessionDurationNotIn(vs ...int) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldSessionDuration, vs...))
}

// SessionDurationGT applies the GT predicate on the "session_duration" field.
func SessionDurationGT(v int) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGT(FieldSessionDuration, v))
}

// SessionDurationGTE applies the GTE predicate on the "session_duration" field.
func SessionDurationGTE(v int) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGTE(FieldSessionDuration, v))
}

// SessionDurationLT applies the LT predicate on the "session_duration" field.
func SessionDurationLT(v int) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLT(FieldSessionDuration, v))
}

// SessionDurationLTE applies the LTE predicate on the "session_duration" field.
func SessionDurationLTE(v int) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLTE(FieldSessionDuration, v))
}

// SessionDurationIsNil applies the IsNil predicate on the "session_duration" field.
func SessionDurationIsNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIsNull(FieldSessionDuration))
}

// SessionDurationNotNil applies the NotNil predicate on the "session_duration" field.
func SessionDurationNotNil() predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotNull(FieldSessionDuration))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProjectView {
	return predicate.ProjectView(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.ProjectView {
	return predicate.ProjectView(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.ProjectView {
	return predicate.ProjectView(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserIdentity applies the HasEdge predicate on the "user_identity" edge.
func HasUserIdentity() predicate.ProjectView {
	return predicate.ProjectView(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserIdentityTable, UserIdentityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserIdentityWith applies the HasEdge predicate on the "user_identity" edge with a given conditions (other predicates).
func HasUserIdentityWith(preds ...predicate.UserIdentity) predicate.ProjectView {
	return predicate.ProjectView(func(s *sql.Selector) {
		step := newUserIdentityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectView) predicate.ProjectView {
	return predicate.ProjectView(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectView) predicate.ProjectView {
	return predicate.ProjectView(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectView) predicate.ProjectView {
	return predicate.ProjectView(sql.NotPredicates(p))
}
