api:
  development:
    base_url: "http://localhost:5200"
    timeout: 30
    retries: 3

  production:
    base_url: "${API_BASE_URL}"
    timeout: 60
    retries: 5

  testing:
    base_url: "http://localhost:5200"
    timeout: 10
    retries: 1

  endpoints:
    blogs: "/api/blogs"
    projects: "/api/projects"
    ideas: "/api/ideas"
    resume: "/api/resume"
    updates: "/api/updates"
    moments: "/api/moments"

  headers:
    content_type: "application/json"
    accept: "application/json"
    user_agent: "Silan/1.0"

  rate_limiting:
    requests_per_minute: 60
    burst_size: 10