database:
  sqlite:
    default_path: "portfolio.db"
    timeout: 30
    check_same_thread: false

  mysql:
    default_port: 3306
    charset: "utf8mb4"
    timeout: 30
    pool_size: 10

  postgresql:
    default_port: 5432
    timeout: 30
    pool_size: 10

  cache:
    file_name: ".silan_cache"
    version: "1.0"

  sync:
    batch_size: 100
    timeout: 300
    retry_attempts: 3