defaults:
  content:
    language: "en"
    author: "Silan Team"

  sync:
    enabled: true
    auto_sync: false

  features:
    interactive_exercises: true
    code_examples: true
    downloadable_resources: true
    community_support: true
    progress_tracking: true

  ui:
    theme: "default"
    show_line_numbers: true
    syntax_highlighting: true

  export:
    formats: ["html", "pdf", "markdown"]
    include_metadata: true

  backup:
    enabled: true
    frequency: "daily"
    retention_days: 30

  security:
    sanitize_input: true
    escape_html: true
    validate_uploads: true