logging:
  theme:
    gradient_start: "#41B883"  # Vue green
    gradient_end: "#6574CD"    # Vue purple
    default_theme:
      primary: "#41B883"
      secondary: "#6574CD"
      success: "#28a745"
      warning: "#ffc107"
      error: "#dc3545"
      info: "#17a2b8"
      light: "#f8f9fa"
      dark: "#343a40"

  levels:
    debug: DEBUG
    info: INFO
    warning: WARNING
    error: ERROR
    critical: CRITICAL

  formats:
    default: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    detailed: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
    simple: "%(levelname)s: %(message)s"