models:
  projects:
    status:
      active: "active"
      completed: "completed"
      paused: "paused"
      cancelled: "cancelled"

  blog:
    types:
      article: "article"
      vlog: "vlog"
      episode: "episode"

    status:
      draft: "draft"
      published: "published"
      archived: "archived"

  ideas:
    status:
      draft: "draft"
      hypothesis: "hypothesis"
      experimenting: "experimenting"
      validating: "validating"
      published: "published"
      concluded: "concluded"

    priority:
      low: "low"
      medium: "medium"
      high: "high"
      urgent: "urgent"

  recent_updates:
    types:
      work: "work"
      education: "education"
      research: "research"
      publication: "publication"
      project: "project"

    status:
      active: "active"
      ongoing: "ongoing"
      completed: "completed"

    priority:
      high: "high"
      medium: "medium"
      low: "low"